application:
	g++ -c application.cpp

border:
	g++ -c border.cpp

container:
	g++ -c container.cpp

daemon:
	g++ -c daemon.cpp

display:
	g++ -c display.cpp

helpers:
	g++ -c helpers.cpp

interpreter:
	g++ -c interpreter.cpp

keys:
	g++ -c keys.cpp

kwm:
	g++ -c kwm.cpp

node:
	g++ -c node.cpp

notifications:
	g++ -c notifications.cpp

serialize:
	g++ -c serialize.cpp

space:
	g++ -c space.cpp

tree:
	g++ -c tree.cpp

window:
	g++ -c window.cpp

windowref:
	g++ -c windowref.cpp

windowtree:
	g++ -c windowtree.cpp

all:
	g++ -c application.cpp border.cpp container.cpp daemon.cpp display.cpp helpers.cpp interpreter.cpp keys.cpp kwm.cpp node.cpp notifications.cpp serialize.cpp space.cpp tree.cpp window.cpp windowref.cpp windowtree.cpp

progress:
	g++ -c container.cpp node.cpp tree.cpp serialize.cpp window.cpp windowref.cpp windowtree.cpp

clean:
	rm -rf ./*.o
