tree:
	g++ -c tree.cpp

node:
	g++ -c node.cpp

container:
	g++ -c container.cpp

display:
	g++ -c display.cpp

window:
	g++ -c window.cpp

windowref:
	g++ -c windowref.cpp

application:
	g++ -c application.cpp

clean:
	rm -rf ./*.o
